language: php

php:
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer install --dev --no-interaction --prefer-dist
  - cp .docker/php/.env.dist .docker/php/.env

script:
  - vendor/bin/phpunit --colors=always
