version: '3.3'

services:
  nginx:
    image: nginx:stable
    volumes:
      - .docker/nginx/tadtech.co.uk.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - 8080:80
    links:
      - php
  php:
    image: php:7-fpm
    env_file: .docker/php/.env
    volumes:
      - .:/app
  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - .:/app
    command: install
